name 'learn_cron'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_cron'
long_description 'Installs/Configures learn_cron'
version '0.1.0'
